# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0002_package_room_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceSearch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('cost', models.CharField(max_length=250)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='RateOfExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('foreign_currency', models.CharField(max_length=250)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pricesearch',
            name='rate_of_exhange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummyapp.RateOfExchange'),
        ),
        migrations.AddField(
            model_name='pricesearch',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummyapp.Room'),
        ),
        migrations.AddField(
            model_name='pricesearch',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummyapp.Supplier'),
        ),
    ]
