# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0004_auto_20160601_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='destination_title',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
