# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0005_package_destination_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='slug',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
