# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0007_auto_20160602_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='slug',
        ),
        migrations.AddField(
            model_name='package',
            name='slug1',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='slug2',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
