# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0009_package_hash_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='hash_1',
            field=models.CharField(editable=False, max_length=10, null=True, unique=True),
        ),
    ]
