# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0010_auto_20160602_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateOfExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rate_of_exchange', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
