# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0013_airportcodesnew'),
    ]

    operations = [
        migrations.AddField(
            model_name='airportcodesnew',
            name='code_new',
            field=models.CharField(default='code', max_length=10),
            preserve_default=False,
        ),
    ]
