# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0014_airportcodesnew_code_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('code', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
