# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-18 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0019_auto_20160616_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='is_voucher_exist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_in',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='destination',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='foreign_currency',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hotel',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='inclusions',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_quoted_in_foreign_currency',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_quoted_in_inr',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tours',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booking',
            name='transfers',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
