# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummyapp', '0022_accommodation_star_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='transfer_type',
            field=models.CharField(default='shared', max_length=250),
        ),
    ]
