# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='duration',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
