# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0002_rate_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateOfExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('rate_of_exchange', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('accommodation', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('duration', models.IntegerField()),
                ('rate_per_person', models.CharField(max_length=255)),
                ('rate_currency', models.CharField(max_length=255)),
                ('tax', models.CharField(blank=True, max_length=255)),
                ('inclusion', models.TextField(blank=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='country',
            name='region',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='country',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.AddField(
            model_name='roomrate',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratesheet.Supplier'),
        ),
    ]
