# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0003_auto_20160601_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='SailingDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('sailing_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
