# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0005_roomrate_is_cruise'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='sailing_date',
            field=models.ManyToManyField(null=True, related_name='cruise_sailing_date', to='ratesheet.SailingDate'),
        ),
    ]
