# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0006_roomrate_sailing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomrate',
            name='is_cruise',
            field=models.BooleanField(default=False),
        ),
    ]
