# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0007_auto_20160601_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomrate',
            old_name='sailing_date',
            new_name='sailing_dates',
        ),
    ]
