# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratesheet', '0009_auto_20160601_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomrate',
            name='surcharge',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
